name: terraform
on:
  push:
    branches:
      - main
  workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      APPLICATION_CLIENT_ID: ${{ secrets.APPLICATION_CLIENT_ID }}
      SECERET_ID: ${{ secrets.SECERET_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      DIRECTORY_TENANT_ID: ${{ secrets.DIRECTORY_TENANT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

